import { StyleSheet } from "@react-pdf/renderer";

// Token visual dan StyleSheet khusus renderer PDF.
export const COLOR = {
  green: "#065F46",
  greenSoft: "#D1FAE5",
  orange: "#F97316",
  yellow: "#FEF08A",
  sand: "#FFFAF0",
  text: "#1E293B",
  muted: "#64748B",
  border: "#E2E8F0",
  grid: "#E5E7EB",
  bgSoft: "#F8FAFC",
  blueSoft: "#EFF6FF",
};

// ── Style global ───────────────────────────────────────────────────────────
export const styles = StyleSheet.create({
  page: {
    paddingTop: 39.7,
    paddingBottom: 39.7,
    paddingHorizontal: 36.9,
    fontSize: 9.75,
    lineHeight: 1.5,
    color: COLOR.text,
    fontFamily: "Helvetica",
    backgroundColor: COLOR.sand,
    position: "relative",
  },
  gridLayer: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  gridVertical: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 0.75,
    backgroundColor: COLOR.grid,
  },
  gridHorizontal: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 0.75,
    backgroundColor: COLOR.grid,
  },
  coverPage: {
    backgroundColor: COLOR.sand,
    color: COLOR.text,
  },
  coverInner: {
    flex: 1,
    paddingVertical: 22.5,
    paddingHorizontal: 15,
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 4.5,
    borderColor: "#FFFFFF",
    borderRadius: 3.75,
  },
  coverBrand: { alignItems: "center" },
  coverLogo: {
    width: 105,
    height: 105,
    objectFit: "contain",
    marginBottom: 10.5,
  },
  coverTitle: {
    fontSize: 36,
    fontFamily: "Helvetica-Bold",
    color: "#2C3E50",
    textAlign: "center",
    lineHeight: 1,
    marginBottom: 9,
  },
  coverSubtitle: {
    fontSize: 11.25,
    fontFamily: "Helvetica-Bold",
    color: COLOR.muted,
    marginTop: 4.5,
  },
  coverSemester: {
    fontSize: 15,
    fontFamily: "Helvetica-Bold",
    color: "#854D0E",
    backgroundColor: COLOR.yellow,
    borderRadius: 30,
    paddingVertical: 4.5,
    paddingHorizontal: 18,
    marginVertical: 6,
  },
  coverStudentCard: {
    width: "80%",
    padding: 15,
    marginVertical: 10.5,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 0.75,
    borderColor: COLOR.border,
    borderRadius: 6,
    position: "relative",
  },
  coverName: {
    fontSize: 22.5,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    marginBottom: 4.5,
  },
  coverFase: { fontSize: 12, color: COLOR.muted, textAlign: "center" },
  coverFooter: {
    paddingVertical: 10.5,
    paddingHorizontal: 21,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#F1F5F9",
    borderRadius: 37.5,
    textAlign: "center",
    fontSize: 9.75,
    fontFamily: "Helvetica-Bold",
    color: "#475569",
  },
  watermark: {
    position: "absolute",
    top: 330,
    left: 170,
    fontSize: 90,
    fontFamily: "Helvetica-Bold",
    color: "#F1EEE7",
    transform: "rotate(-30deg)",
  },
  stickerStar: {
    position: "absolute",
    top: 22.5,
    left: 22.5,
    zIndex: 5,
  },
  stickerRocket: {
    position: "absolute",
    top: 60,
    right: 45,
    zIndex: 5,
    transform: "rotate(-35deg)",
  },
  washiTape: {
    position: "absolute",
    top: -9,
    left: "50%",
    marginLeft: -41.25,
    width: 82.5,
    height: 18,
    backgroundColor: "#FBCFE899",
    borderLeftWidth: 1.5,
    borderRightWidth: 1.5,
    borderColor: "#0000001A",
    borderStyle: "dashed",
    transform: "rotate(-3deg)",
  },
  numberBadge: {
    width: 40.5,
    height: 40.5,
    borderRadius: 12,
    backgroundColor: "#FCA5A5",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: -15,
    zIndex: 2,
  },
  numberBadgeText: {
    color: "#FFFFFF",
    fontSize: 19.5,
    fontFamily: "Helvetica-Bold",
  },
  sectionTitle: {
    alignSelf: "flex-start",
    fontSize: 21,
    fontFamily: "Helvetica-Bold",
    color: COLOR.green,
    backgroundColor: COLOR.greenSoft,
    borderRadius: 37.5,
    paddingVertical: 3.75,
    paddingHorizontal: 16.5,
    marginBottom: 13.5,
  },
  h2: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginTop: 12,
    marginBottom: 6,
  },
  h3: {
    fontSize: 11.5,
    fontFamily: "Helvetica-Bold",
    marginTop: 8,
    marginBottom: 4,
  },
  muted: { color: COLOR.muted },
  italic: { fontFamily: "Helvetica-Oblique" },
  bold: { fontFamily: "Helvetica-Bold" },
  hr: {
    borderBottomWidth: 0.75,
    borderBottomColor: "#CBD5E1",
    marginBottom: 7.5,
  },
  rowProfile: {
    flexDirection: "row",
    paddingVertical: 3.75,
    borderBottomWidth: 0.75,
    borderBottomColor: COLOR.border,
  },
  rowProfileLabel: { width: 127.5, color: COLOR.muted, fontFamily: "Helvetica-Bold" },
  rowProfileValue: { flex: 1, color: COLOR.text },
  profileCard: {
    backgroundColor: COLOR.bgSoft,
    paddingVertical: 10.5,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginVertical: 7.5,
    borderWidth: 0.75,
    borderColor: COLOR.border,
    alignItems: "center",
  },
  profileAvatar: {
    width: 82.5,
    height: 82.5,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  profileAvatarText: {
    fontSize: 34.5,
    color: "#FFFFFF",
    fontFamily: "Helvetica-Bold",
  },
  profileRows: { width: "100%", marginTop: 1.5 },
  table: {
    marginVertical: 9,
    backgroundColor: "#FFFFFF",
    borderWidth: 0.75,
    borderColor: "#EEEEEE",
  },
  tr: { flexDirection: "row", borderBottomWidth: 0.75, borderBottomColor: "#EEEEEE" },
  thead: {
    backgroundColor: "#F9FAFB",
    borderBottomWidth: 1.5,
    borderBottomColor: "#EEEEEE",
  },
  th: {
    fontFamily: "Helvetica-Bold",
    paddingVertical: 6,
    paddingHorizontal: 7.5,
    fontSize: 9,
  },
  td: { paddingVertical: 6, paddingHorizontal: 7.5, fontSize: 9.4 },
  box: {
    borderWidth: 0.75,
    borderColor: COLOR.border,
    borderRadius: 12,
    paddingVertical: 10.5,
    paddingHorizontal: 12,
    backgroundColor: COLOR.bgSoft,
    marginVertical: 7.5,
  },
  predikatBox: {
    backgroundColor: "#DCFCE7",
    color: COLOR.text,
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderWidth: 2.25,
    borderColor: "#FFFFFF",
    borderRadius: 18,
    marginVertical: 7.5,
  },
  predikatTitle: {
    fontSize: 13.5,
    fontFamily: "Helvetica-Bold",
    color: COLOR.green,
    marginBottom: 3,
  },
  predikatText: { fontSize: 9.75, color: "#374151" },
  blueBubble: {
    backgroundColor: COLOR.blueSoft,
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 18,
    marginVertical: 9,
    borderWidth: 2.25,
    borderColor: "#FFFFFF",
  },
  statGrid: { flexDirection: "row", gap: 12, marginVertical: 9 },
  statBox: {
    flex: 1,
    backgroundColor: COLOR.bgSoft,
    padding: 12,
    borderRadius: 12,
    borderWidth: 0.75,
    borderColor: COLOR.border,
    alignItems: "center",
  },
  statLabel: { fontSize: 9.75, color: COLOR.muted, marginBottom: 4.5 },
  statValue: { fontSize: 27, fontFamily: "Helvetica-Bold", lineHeight: 1 },
  footerCaption: {
    marginTop: "auto",
    textAlign: "center",
    paddingTop: 10.5,
    borderTopWidth: 0.75,
    borderTopColor: COLOR.border,
    borderStyle: "dashed",
  },
  pageFooter: {
    position: "absolute",
    bottom: 20,
    left: 36.9,
    right: 36.9,
    fontSize: 8,
    color: COLOR.muted,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 0.75,
    borderTopColor: "#CBD5E1",
    paddingTop: 4,
  },
});
